// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: operations.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOperation) Reset() {
	*x = SetOperation{}
	mi := &file_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperation) ProtoMessage() {}

func (x *SetOperation) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperation.ProtoReflect.Descriptor instead.
func (*SetOperation) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{0}
}

func (x *SetOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetOperation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetOperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOperationResult) Reset() {
	*x = SetOperationResult{}
	mi := &file_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperationResult) ProtoMessage() {}

func (x *SetOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperationResult.ProtoReflect.Descriptor instead.
func (*SetOperationResult) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{1}
}

type GetOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperation) Reset() {
	*x = GetOperation{}
	mi := &file_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperation) ProtoMessage() {}

func (x *GetOperation) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperation.ProtoReflect.Descriptor instead.
func (*GetOperation) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetOperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResult) Reset() {
	*x = GetOperationResult{}
	mi := &file_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResult) ProtoMessage() {}

func (x *GetOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResult.ProtoReflect.Descriptor instead.
func (*GetOperationResult) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{3}
}

func (x *GetOperationResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DelOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelOperation) Reset() {
	*x = DelOperation{}
	mi := &file_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOperation) ProtoMessage() {}

func (x *DelOperation) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOperation.ProtoReflect.Descriptor instead.
func (*DelOperation) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{4}
}

func (x *DelOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelOperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelOperationResult) Reset() {
	*x = DelOperationResult{}
	mi := &file_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOperationResult) ProtoMessage() {}

func (x *DelOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOperationResult.ProtoReflect.Descriptor instead.
func (*DelOperationResult) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{5}
}

type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Operation_SetOperation
	//	*Operation_GetOperation
	//	*Operation_DelOperation
	Operation     isOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{6}
}

func (x *Operation) GetOperation() isOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Operation) GetSetOperation() *SetOperation {
	if x != nil {
		if x, ok := x.Operation.(*Operation_SetOperation); ok {
			return x.SetOperation
		}
	}
	return nil
}

func (x *Operation) GetGetOperation() *GetOperation {
	if x != nil {
		if x, ok := x.Operation.(*Operation_GetOperation); ok {
			return x.GetOperation
		}
	}
	return nil
}

func (x *Operation) GetDelOperation() *DelOperation {
	if x != nil {
		if x, ok := x.Operation.(*Operation_DelOperation); ok {
			return x.DelOperation
		}
	}
	return nil
}

type isOperation_Operation interface {
	isOperation_Operation()
}

type Operation_SetOperation struct {
	SetOperation *SetOperation `protobuf:"bytes,1,opt,name=set_operation,json=setOperation,proto3,oneof"`
}

type Operation_GetOperation struct {
	GetOperation *GetOperation `protobuf:"bytes,2,opt,name=get_operation,json=getOperation,proto3,oneof"`
}

type Operation_DelOperation struct {
	DelOperation *DelOperation `protobuf:"bytes,3,opt,name=del_operation,json=delOperation,proto3,oneof"`
}

func (*Operation_SetOperation) isOperation_Operation() {}

func (*Operation_GetOperation) isOperation_Operation() {}

func (*Operation_DelOperation) isOperation_Operation() {}

type OperationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to OperationResult:
	//
	//	*OperationResult_SetOperationResult
	//	*OperationResult_GetOperationResult
	//	*OperationResult_DelOperationResult
	OperationResult isOperationResult_OperationResult `protobuf_oneof:"operation_result"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{7}
}

func (x *OperationResult) GetOperationResult() isOperationResult_OperationResult {
	if x != nil {
		return x.OperationResult
	}
	return nil
}

func (x *OperationResult) GetSetOperationResult() *SetOperationResult {
	if x != nil {
		if x, ok := x.OperationResult.(*OperationResult_SetOperationResult); ok {
			return x.SetOperationResult
		}
	}
	return nil
}

func (x *OperationResult) GetGetOperationResult() *GetOperationResult {
	if x != nil {
		if x, ok := x.OperationResult.(*OperationResult_GetOperationResult); ok {
			return x.GetOperationResult
		}
	}
	return nil
}

func (x *OperationResult) GetDelOperationResult() *DelOperationResult {
	if x != nil {
		if x, ok := x.OperationResult.(*OperationResult_DelOperationResult); ok {
			return x.DelOperationResult
		}
	}
	return nil
}

type isOperationResult_OperationResult interface {
	isOperationResult_OperationResult()
}

type OperationResult_SetOperationResult struct {
	SetOperationResult *SetOperationResult `protobuf:"bytes,1,opt,name=set_operation_result,json=setOperationResult,proto3,oneof"`
}

type OperationResult_GetOperationResult struct {
	GetOperationResult *GetOperationResult `protobuf:"bytes,2,opt,name=get_operation_result,json=getOperationResult,proto3,oneof"`
}

type OperationResult_DelOperationResult struct {
	DelOperationResult *DelOperationResult `protobuf:"bytes,3,opt,name=del_operation_result,json=delOperationResult,proto3,oneof"`
}

func (*OperationResult_SetOperationResult) isOperationResult_OperationResult() {}

func (*OperationResult_GetOperationResult) isOperationResult_OperationResult() {}

func (*OperationResult_DelOperationResult) isOperationResult_OperationResult() {}

var File_operations_proto protoreflect.FileDescriptor

const file_operations_proto_rawDesc = "" +
	"\n" +
	"\x10operations.proto\x12\x05store\"6\n" +
	"\fSetOperation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x14\n" +
	"\x12SetOperationResult\" \n" +
	"\fGetOperation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x12GetOperationResult\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\" \n" +
	"\fDelOperation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x14\n" +
	"\x12DelOperationResult\"\xcc\x01\n" +
	"\tOperation\x12:\n" +
	"\rset_operation\x18\x01 \x01(\v2\x13.store.SetOperationH\x00R\fsetOperation\x12:\n" +
	"\rget_operation\x18\x02 \x01(\v2\x13.store.GetOperationH\x00R\fgetOperation\x12:\n" +
	"\rdel_operation\x18\x03 \x01(\v2\x13.store.DelOperationH\x00R\fdelOperationB\v\n" +
	"\toperation\"\x92\x02\n" +
	"\x0fOperationResult\x12M\n" +
	"\x14set_operation_result\x18\x01 \x01(\v2\x19.store.SetOperationResultH\x00R\x12setOperationResult\x12M\n" +
	"\x14get_operation_result\x18\x02 \x01(\v2\x19.store.GetOperationResultH\x00R\x12getOperationResult\x12M\n" +
	"\x14del_operation_result\x18\x03 \x01(\v2\x19.store.DelOperationResultH\x00R\x12delOperationResultB\x12\n" +
	"\x10operation_resultB\x06Z\x04./pbb\x06proto3"

var (
	file_operations_proto_rawDescOnce sync.Once
	file_operations_proto_rawDescData []byte
)

func file_operations_proto_rawDescGZIP() []byte {
	file_operations_proto_rawDescOnce.Do(func() {
		file_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operations_proto_rawDesc), len(file_operations_proto_rawDesc)))
	})
	return file_operations_proto_rawDescData
}

var file_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_operations_proto_goTypes = []any{
	(*SetOperation)(nil),       // 0: store.SetOperation
	(*SetOperationResult)(nil), // 1: store.SetOperationResult
	(*GetOperation)(nil),       // 2: store.GetOperation
	(*GetOperationResult)(nil), // 3: store.GetOperationResult
	(*DelOperation)(nil),       // 4: store.DelOperation
	(*DelOperationResult)(nil), // 5: store.DelOperationResult
	(*Operation)(nil),          // 6: store.Operation
	(*OperationResult)(nil),    // 7: store.OperationResult
}
var file_operations_proto_depIdxs = []int32{
	0, // 0: store.Operation.set_operation:type_name -> store.SetOperation
	2, // 1: store.Operation.get_operation:type_name -> store.GetOperation
	4, // 2: store.Operation.del_operation:type_name -> store.DelOperation
	1, // 3: store.OperationResult.set_operation_result:type_name -> store.SetOperationResult
	3, // 4: store.OperationResult.get_operation_result:type_name -> store.GetOperationResult
	5, // 5: store.OperationResult.del_operation_result:type_name -> store.DelOperationResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_operations_proto_init() }
func file_operations_proto_init() {
	if File_operations_proto != nil {
		return
	}
	file_operations_proto_msgTypes[6].OneofWrappers = []any{
		(*Operation_SetOperation)(nil),
		(*Operation_GetOperation)(nil),
		(*Operation_DelOperation)(nil),
	}
	file_operations_proto_msgTypes[7].OneofWrappers = []any{
		(*OperationResult_SetOperationResult)(nil),
		(*OperationResult_GetOperationResult)(nil),
		(*OperationResult_DelOperationResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operations_proto_rawDesc), len(file_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operations_proto_goTypes,
		DependencyIndexes: file_operations_proto_depIdxs,
		MessageInfos:      file_operations_proto_msgTypes,
	}.Build()
	File_operations_proto = out.File
	file_operations_proto_goTypes = nil
	file_operations_proto_depIdxs = nil
}
